# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 764)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 10, 681, 641))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")

        # Création des instances de QButtonGroup
        self.buttonGroup1 = QtWidgets.QButtonGroup(MainWindow)  # Groupe pour les types de messages
        self.buttonGroup2 = QtWidgets.QButtonGroup(MainWindow)  # Groupe pour les types d'encodage

        # Configuration du layout horizontal principal
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        # Layout vertical pour les types de messages
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelMessage = QtWidgets.QLabel(self.widget)
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelMessage.setFont(font)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_2.addWidget(self.labelMessage)

        # Boutons radio pour les types de messages
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.radioText = QtWidgets.QRadioButton(self.widget)
        self.radioText.setFont(font)
        self.radioText.setObjectName("radioText")
        self.verticalLayout_2.addWidget(self.radioText)
        self.buttonGroup1.addButton(self.radioText)

        self.radioImg = QtWidgets.QRadioButton(self.widget)
        self.radioImg.setFont(font)
        self.radioImg.setObjectName("radioImg")
        self.verticalLayout_2.addWidget(self.radioImg)
        self.buttonGroup1.addButton(self.radioImg)

        self.radioServer = QtWidgets.QRadioButton(self.widget)
        self.radioServer.setFont(font)
        self.radioServer.setObjectName("radioServer")
        self.verticalLayout_2.addWidget(self.radioServer)
        self.buttonGroup1.addButton(self.radioServer)

        self.horizontalLayout.addLayout(self.verticalLayout_2)

        # Layout vertical pour les types d'encodage
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelEncoding = QtWidgets.QLabel(self.widget)
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelEncoding.setFont(font)
        self.labelEncoding.setObjectName("labelEncoding")
        self.verticalLayout.addWidget(self.labelEncoding)

        # Boutons radio pour les types d'encodage
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.radioNone = QtWidgets.QRadioButton(self.widget)
        self.radioNone.setFont(font)
        self.radioNone.setObjectName("radioNone")
        self.verticalLayout.addWidget(self.radioNone)
        self.buttonGroup2.addButton(self.radioNone)

        self.radioShift = QtWidgets.QRadioButton(self.widget)
        self.radioShift.setFont(font)
        self.radioShift.setObjectName("radioShift")
        self.verticalLayout.addWidget(self.radioShift)
        self.buttonGroup2.addButton(self.radioShift)

        self.radioXor = QtWidgets.QRadioButton(self.widget)
        self.radioXor.setFont(font)
        self.radioXor.setObjectName("radioXor")
        self.verticalLayout.addWidget(self.radioXor)
        self.buttonGroup2.addButton(self.radioXor)

        self.radioRSA = QtWidgets.QRadioButton(self.widget)
        self.radioRSA.setFont(font)
        self.radioRSA.setObjectName("radioRSA")
        self.verticalLayout.addWidget(self.radioRSA)
        self.buttonGroup2.addButton(self.radioRSA)

        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        # Autres widgets pour affichage et entrée de message
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.messageDisplay = QtWidgets.QTextEdit(self.widget)
        self.messageDisplay.setReadOnly(True)
        self.messageDisplay.setObjectName("messageDisplay")
        self.horizontalLayout_2.addWidget(self.messageDisplay)
        self.messageInput = QtWidgets.QTextEdit(self.widget)
        self.messageInput.setObjectName("messageInput")
        self.horizontalLayout_2.addWidget(self.messageInput)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        # Bouton d'envoi
        self.sendButton = QtWidgets.QPushButton(self.widget)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.gridLayout.addWidget(self.sendButton, 2, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA Encryption Tool"))
        self.labelMessage.setText(_translate("MainWindow", "Message Type:"))
        self.radioText.setText(_translate("MainWindow", "Text"))
        self.radioImg.setText(_translate("MainWindow", "Image"))
        self.radioServer.setText(_translate("MainWindow", "Server"))
        self.labelEncoding.setText(_translate("MainWindow", "Encoding Type:"))
        self.radioNone.setText(_translate("MainWindow", "None"))
        self.radioShift.setText(_translate("MainWindow", "Shift"))
        self.radioXor.setText(_translate("MainWindow", "Xor"))
        self.radioRSA.setText(_translate("MainWindow", "RSA"))
        self.sendButton.setText(_translate("MainWindow", "Send"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
